### PR TITLE
[BUGFIX] Avoid JS error if unminified versions are used

### PR DESCRIPTION
**Pull request by webian**
Setting plugin.tx_cookieman.settings.minify=0 causes JS error:
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(intermediate value)(...) is not a function

### CODE REVIEW

**Comment by jonaseberle** [comment]
Hi, I cannot reproduce. Which browser are you using?

Is there maybe something else in the game like for example EXT:scriptmerger or a build system?

I've set the constant `plugin.tx_cookieman.settings.minify = 0` temporarily on https://cookieman.d-mind.de/ if you want to try there.

**Comment by webian** [comment]
Hi @jonaseberle, please can you test it again with bootstrap 3?
I guess it is related to: EXT:cookieman/Resources/Public/Themes/bootstrap3-modal/cookieman-theme.js

**Comment by jonaseberle** [comment]
Hi @webian you can see the default themes here:
https://cookieman.d-mind.de/theme-bootstrap3-banner and https://cookieman.d-mind.de/theme-bootstrap3-modal

The BS3 default themes are far from perfect and that site misses the Bootstrap-glyphicons, but there are no JS errors.

> Is there maybe something else in the game like for example EXT:scriptmerger or a build system?
Have you checked that?

**Comment by webian** [comment]
Not EXT:scriptmerger or a build system but I just noticed that the difference between my setup and your is that in mine TYPO3 merges the JS files (typical /typo3temp/assets/compressed/merged-....js file)

**Comment by jonaseberle** [comment]
Is it this setting? https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Setup/Config/Index.html#compressjs

I never use it because I don't think it is necessary any more with HTTP/2+ and because I had problems with it earlier.

But since it is still in the Core I am willing to make it work and if your change makes it work we can have that.

**Comment by jonaseberle** [comment]
Related: https://github.com/dmind-gmbh/extension-cookieman/issues/267

**Comment by jonaseberle** [comment]
@webian could you check if it is dependant on those TYPO3 settings?

**Comment by webian** [comment]
Yes @jonaseberle, I have those 2 setting on.

**Comment by jonaseberle** [comment]
Ok. I would consider it a bug with `config.concatenateJs`, found a simple MRE and added a ticket: https://forge.typo3.org/issues/99503

Let's merge this here anyways. Thanks.

**Comment by jonaseberle** [comment]
@webian I could not reproduce a problem with concatenation with files in TYPO3 `main` and `10.4`.

I have tried with 
```
config.concatenateJs = 1
config.compressJs = 1

page.includeJS {
  5 = fileadmin/cookieman.js
  10 = fileadmin/script1.js
  20 = fileadmin/script2.js
}
```
with all of those files without the trailing comma.

They get neatly concatenated with a line break in between:
```
...
        eventsEl: eventsEl
    }
}())

alert('script1')
```

How does your setup differ to produce a problem? Could you have a look how the last part of cookieman.js and the part of the following file look like in your concatenated file?

**Comment by webian** [comment]
@jonaseberle I can reproduce it in TYPO3 11 LTS with this MRE:
```
config >
page >
config.concatenateJs = 1
config.compressJs = 1

page = PAGE
page.includeJS {
    10 = fileadmin/script1.js
    20 = fileadmin/script2.js
}
```

script1.js (extract from EXT:cookieman/Resources/Public/Js/cookieman.js)
```
var cookieman = (function () {
}())
```

script2.js (extract from EXT:cookieman/Resources/Public/Themes/bootstrap3-modal/cookieman-theme.js
```
(function () {
})()
```

Hope it helps.

**Comment by webian** [comment]
I add that the content of the merged file is:
```
var cookieman = (function () {
}())

(function () {
})()
```

causing JS error:
`Uncaught TypeError: (intermediate value)(...) is not a function`

**Comment by jonaseberle** [comment]
Ah, I see. thanks for checking. So it's not about the following code, but the code in front if the [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE?retiredLocale=de). We actually introduced the problem by removing the (unused) variable assignment `cookieman.theme =` in https://github.com/dmind-gmbh/extension-cookieman/commit/a076d2d58ca4ab130eaabdcb6f7e52d508f8f54d ...

**Pull request merged**
