### PR TITLE
Update de.locallang.xlf

### PR DESCRIPTION
**Pull request by stwagner**
fix minor orthographic issues and adds optional hyphenation to improve layout

### CODE REVIEW

**Comment by jonaseberledmind** [comment]
Thank you very much for the contribution! Wow, the shy-hyphens are great! 
I agree on the wording change, too.

We manage our translations on [Crowdin](https://crowdin.com/project/typo3-extension-cookieman). If it's ok for you, would you change the string there?

**Comment by jonaseberledmind** [comment]
Dear @stwagner, the `&shy;` hyphens will unfortunately not be rendered when using the default Fluid Translate-Viewhelper https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3/fluid/latest/Translate.html - we would have to wrap each and every one in `<f:format.raw>` which seems a little overkill.

I'll leave the translations in as they are but was a bit surprised that your pull request included them.

Thank you.

**Comment by stwagner** [comment]
Hi Jonas, <f:format:raw> would be indeed an overkill, even the <!CDATA[]> is ugly and uncommon. 
I was happy that it is working and shared my modifications. I'm not aware that I have modified my Translate-Viewhelper.
Thank you for review and plugin!

**Comment by jonaseberledmind** [comment]
Happy that you like the extension :)

**Pull request closed without merging**
