### PR TITLE
[DOCS] Fix formatting problems in docs

### PR DESCRIPTION
**Pull request by sypets**
In reStructuredTexts lists must have a previous and following newline.
Otherwise this may not get rendered correctly.

Underlines should always be at least as long as the section header text.

----

The following is not part of the commit message:

Example how the list is rendering with missing newlines (starting with "Supported TYPO3 versions"):

image

**Additional tips:**

* see common pitfalls for reStructuredText: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/BasicRestSyntax.html
* if you have CONTRIBUTING.rst / CONTRIBUTING.md, this will automatically be shown on GitHub (e.g. if you click on the Issues section). This is a tradeoff - either the contributing info is shown on GitHub or you have it nicely rendered withing the docs, but you can use a combination: Hava a placeholder CONTRIBUTING.rst and in that link to the contribution section in the docs.
* The rendering errrors are shown in warnings.txt:

[run the rendering locally](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/RenderingDocs/Index.html) will show you the path to warnings.txt:

```
Find the results:
  ./Documentation-GENERATED-temp/Result/project/0.0.0/Index.html
  ./Documentation-GENERATED-temp/Result/project/0.0.0/_buildinfo
  ./Documentation-GENERATED-temp/Result/project/0.0.0/_buildinfo/warnings.txt

```

cat Documentation-GENERATED-temp/Result/project/0.0.0/_buildinfo/warnings.txt
```
..
/Documentation/Configuration/Customization/Index.rst:92: WARNING: Title underline too short.

<* data-cookieman-accept-none>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
./Documentation/Configuration/Customization/Index.rst:92: WARNING: Title underline too short.
..
```

* Alternatively, you can also add GitHub actions for rendering docs, as done in the official documentation.

Btw, kudos for having an "Edit on GitHub" button and information for contributors. Not many extension authors do this.

### CODE REVIEW

**Comment by jonaseberle** [comment]
Thank you Sybille! 

Those are very valuable hints for me. Thank you for fixing the problems!

I would like to use a .rst linter and keep an eye on https://github.com/TYPO3-Documentation/tea/blob/main/composer.json#L108 if they implement one. But you just got me the idea that I could automatically check if the `warnings.txt` is empty after rendering.

We use Github actions doc rendering already https://github.com/dmind-gmbh/extension-cookieman/actions/runs/1244882039 - but I use the local docker way when I change something. I must check for build errors in the future!

Thank you!

**Comment by jonaseberle** [comment]
Oh, I see we forgot the `CONTRIBUTING.rst` - does that have to be on the root level or could it be in `/Documentation`?

**Comment by sypets** [comment]
> Oh, I see we forgot the CONTRIBUTING.rst - does that have to be on the root level or could it be in /Documentation?

**Please beware: My knowledge currently is probably outdated. Also it is partially based on trial and error.**

If you find out something, I would appreciate if you let me know or contribute. Here is the official docs for adding the file CONTRIBUTING to TYPO3 docs: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#contributing-rst

-----

GitHub recognizes it, if it is on the root level. Either CONTRIBUTING.rst or CONTRIBUTING.md) should work. 

The [official docs of GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) say it should be in the root folder,  `docs` (not `Documentation`) or `.github` folder (see also [github/docs](https://github.com/github/docs)). 

The problem is, it is a little difficult to test the result because the behaviour on GitHub depends on the user. For example - what I found out by trial and error - GitHub may show a notice on the side and in the issues tab with a link to your contribution guidelines - but **you may not see this if you contributed yourself or are maintainer / owner of repo** (not sure which is relevant or if it is something else).

For example look at some of the official docs repos: 

* https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues

All of these should have a CONTRIBUTING.rst / or md. 

I never really found this documented well by GitHub. What I "know" now is mostly by trial and error.

Another example: https://github.com/atom/atom/blob/master/CONTRIBUTING.md

image

**Comment by jonaseberle** [comment]
Thank you, I think `.github/CONTRIBUTING.rst` will do it for us.
I've added one with a link to the contributor's page in the docs.
https://github.com/dmind-gmbh/extension-cookieman/commit/0bba81ad7fcad1ac86e3d883f2eec8d405483f13

**Comment by sypets** [comment]
> I would like to use a .rst linter

Yes, it seems to me it would be a huge help for the TYPO3 community if checking and fixing CGL and formatting problems in .rst files were as easy as in PHP files. 

Also, some people insist on using markdown (because rst is considered complicated). With better tool support for .rst this would be moot, I think. 

(I don't mind if they use .md but all these difference in "how we do things" effectively makes contributing more difficult and is ineffecient because available peoplepower is split up - though in some cases it might accellerate innovation due to competition).

You may want to get in touch with the docs team in `#typo3-documentation` and check if anyone is working on this (.rst lint, .rst CGL fix) already or if there are solutions available. I am not entirely in touch with the latest developments. All I know is I already supplied patches to the changelog files in the core several times (similar to the fixes here). One of the problems even prevented rendering the changelog. So I assume improvement here would really help and avoid tedious and boring tasks.

Ideal would be if some of the problems were already picked up by PhpStorm and shown in the GUI. There is a reStructuredText plugin available but rst != sphinx. We use sphinx and some additional markup for this. Also the plugin does not detect and show all problems.

Hope it is ok that I gave more than my 2c here. Have a nice day :smile:

**Pull request merged**
