### PR TITLE
[FEATURE] Use <f:spaceless> to reduce output (#255)

### PR DESCRIPTION
**Pull request by cundd**

### CODE REVIEW

**Comment by cundd** [comment]
The output could be compressed even further with a more aggressive View Helper. But it would maybe break some styles: 

```

use Closure;
use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
use TYPO3Fluid\Fluid\ViewHelpers\SpacelessViewHelper;

/**
 * An aggressive space-eliminating View Helper
 *
 * @experimental
 */
class SpacecrunchViewHelper extends SpacelessViewHelper
{
    /**
     * An aggressive space-eliminating View Helper
     *
     * @param array                     $arguments
     * @param Closure                   $childClosure
     * @param RenderingContextInterface $renderingContext
     * @return string
     */
    public static function renderStatic(
        array $arguments,
        Closure $childClosure,
        RenderingContextInterface $renderingContext
    ): string {
        $parent = parent::renderStatic($arguments, $childClosure, $renderingContext);

        return trim(preg_replace('/(\s)\s+/', ' ', $parent));
    }
}
```

**Comment by jonaseberle** [comment]
It saves around 20% of raw size but gzipped it's only ~5% on the default TYPO3 Welcome page. 

image

image

Let's have it. If you want to experiment with a better ViewHelper: Even if we load the rendered Fluid template via AJAX any reduction is welcome :)

**Comment by jonaseberle** [comment]
Just tell me if you need a cookieman release.
I am backporting to v10 and v9.

**Comment by jonaseberle** [comment]
Thank you very much!

**Comment by cundd** [comment]
For me an explicit release is not necessary. I just thought it could be useful for the future.

Thank you for the merge and thank you very much for this very useful extension!

**Pull request merged**
